# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0003_photo_ipadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='poster',
            field=models.CharField(default='anon', max_length=50),
        ),
    ]
