# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0004_auto_20161220_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photoURL',
        ),
    ]
