# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0007_comments_ipadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
