# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0009_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default='anon', max_length=50),
        ),
    ]
