# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0010_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='bio',
            field=models.CharField(default='', max_length=255),
        ),
    ]
