# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0011_profil_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='reieving',
            new_name='reciever',
        ),
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
