# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0012_auto_20170109_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='', max_length=125),
        ),
    ]
