# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0014_auto_20170110_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='postedBy',
        ),
        migrations.AlterField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(default='anon', max_length=80),
        ),
    ]
