# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0016_auto_20170202_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profileImg',
            field=models.CharField(default='', max_length=40),
        ),
    ]
