# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0017_profil_profileimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
