# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpp', '0018_auto_20170202_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
