# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('ipadd', models.CharField(default='anon', max_length=50)),
                ('user', models.CharField(default='anon', max_length=80)),
                ('photouuid', models.UUIDField(default=None)),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='anon', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('poster', models.CharField(default='anon', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(default='Tuvalvu', max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('ipadd', models.CharField(default='anon', max_length=50)),
                ('caption', models.CharField(default='', max_length=125)),
            ],
        ),
    ]
