# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='anontoken',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='messages',
            name='anontoken',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='anontoken',
            field=models.CharField(default='', max_length=50),
        ),
    ]
