# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tokenkey',
        ),
        migrations.AddField(
            model_name='profile',
            name='deviceuuid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
