# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0005_auto_20170420_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='anontoken',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='ipadd',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='anontoken',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='ipadd',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='place',
        ),
    ]
