# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qapp', '0006_auto_20170423_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('isanon', models.BooleanField(default=False)),
                ('bio', models.CharField(default='', max_length=255)),
                ('profileImg', models.CharField(default='', max_length=40)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
