# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='active',
        ),
    ]
