# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0008_remove_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='authtoken',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='authtoken',
            field=models.CharField(default='', max_length=50),
        ),
    ]
