# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0009_auto_20170426_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='authtoken',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='authtoken',
        ),
        migrations.AddField(
            model_name='comments',
            name='useruuid',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='photo',
            name='useruuid',
            field=models.CharField(default='', max_length=125),
        ),
    ]
