# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0010_auto_20170427_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='useruuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='useruuid',
            field=models.UUIDField(),
        ),
    ]
