# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profil',
            name='deposit_add',
            field=models.CharField(default=0, max_length=35),
        ),
        migrations.AddField(
            model_name='profil',
            name='withdrawal_add',
            field=models.CharField(default=0, max_length=35),
        ),
    ]
