# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0003_sysvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysvar',
            name='btcPrice',
            field=models.IntegerField(default=10),
        ),
    ]
