# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0004_auto_20160828_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysvar',
            name='btcPrice',
            field=models.CharField(default=10, max_length=40),
        ),
    ]
