# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0006_buyurls_escrowpayoutledger_sellurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellurls',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
