# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0007_sellurls_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurls',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
    ]
