# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0008_auto_20160912_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellurls',
            name='escrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='escrowpayoutledger',
            name='escrow',
            field=models.BooleanField(default=False),
        ),
    ]
