# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('btc', '0009_auto_20160912_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayoutledger',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to=settings.AUTH_USER_MODEL),
        ),
    ]
