# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0010_escrowpayoutledger_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurls',
            name='mozscore',
        ),
        migrations.RemoveField(
            model_name='buyurls',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sellurls',
            name='activelink',
        ),
        migrations.RemoveField(
            model_name='sellurls',
            name='escrow',
        ),
        migrations.RemoveField(
            model_name='sellurls',
            name='validated',
        ),
        migrations.AddField(
            model_name='buyurls',
            name='activelink',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='buyurls',
            name='escrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurls',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellurls',
            name='mozscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellurls',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='buyurls',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backlink', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellurls',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webpage', to=settings.AUTH_USER_MODEL),
        ),
    ]
