# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0011_auto_20160913_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellurls',
            name='subpage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellurls',
            name='tag1',
            field=models.CharField(default=None, max_length=35),
        ),
        migrations.AddField(
            model_name='sellurls',
            name='tag2',
            field=models.CharField(default=None, max_length=35),
        ),
        migrations.AddField(
            model_name='sellurls',
            name='tag3',
            field=models.CharField(default=None, max_length=35),
        ),
        migrations.AddField(
            model_name='sellurls',
            name='tag4',
            field=models.CharField(default=None, max_length=35),
        ),
        migrations.AddField(
            model_name='sellurls',
            name='tag5',
            field=models.CharField(default=None, max_length=35),
        ),
    ]
