# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0012_auto_20160915_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurls',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escrowpayoutledger',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellurls',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
