# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0013_auto_20160915_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='referer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellurls',
            name='listed',
            field=models.BooleanField(default=False),
        ),
    ]
