# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0014_auto_20160917_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
