# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0015_auto_20160917_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='id',
            new_name='myuuid',
        ),
    ]
