# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0018_auto_20160919_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellurls',
            old_name='tag1',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='sellurls',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='sellurls',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='sellurls',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='sellurls',
            name='tag5',
        ),
    ]
