# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0021_auto_20160921_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escrowpayoutledger',
            old_name='timestampval',
            new_name='timestampofval',
        ),
        migrations.RenameField(
            model_name='escrowpayoutledger',
            old_name='timestampval30',
            new_name='timestampofval30',
        ),
    ]
