# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0022_auto_20160922_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowpayoutledger',
            name='timestampofval',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='escrowpayoutledger',
            name='timestampofval30',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
