# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0023_auto_20160923_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayoutledger',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='in_escrow',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profil',
            name='wif',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='sysvar',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
