# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0024_auto_20161013_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayoutledger',
            name='domain',
            field=models.URLField(default=None),
        ),
    ]
